apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  annotations:
    # cert-manager.io/cluster-issuer: letsencrypt-staging
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - customer1.mercury.peejay-tech.com
      secretName: n8n-tls-prod
  rules:
    - host: customer1.mercury.peejay-tech.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n # Your n8n service name
                port:
                  number: 3008 # Or whatever port your n8n service exposes
